version: '3'
services:
  orange-talents-04-template-ecommerce:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: orange-talents-04-template-ecommerce
    ports:
    - '8080:8080'
    - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,addres=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql:5.7
    ports:
    - '3308:3308'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=merdadolivre
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
    - ./docker/volume_mysql/var/lib/mysql